apiVersion: v1
kind: Secret
metadata:
  name: tropical-bawah-secret
  namespace: test-app
type: Opaque
stringData:
  APP_KEY: "base64:GENERATE_YOUR_APP_KEY"
  DB_DATABASE: "tropicalos"
  DB_USERNAME: "tropicalos"
  DB_PASSWORD: "CHANGE_ME"
  GEMINI_API_KEY: ""
