apiVersion: batch/v1
kind: Job
metadata:
  name: tropical-bawah-seed
  namespace: test-app
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: tropical-bawah-seed
    spec:
      restartPolicy: Never

      hostAliases:
        - ip: "__DB_IP__"
          hostnames:
            - "__DB_HOST__"

      containers:
        - name: seed
          image: __API_IMAGE__
          imagePullPolicy: Always

          command:
            - php
            - artisan
            - db:seed
            - --force

          envFrom:
            - configMapRef:
                name: tropical-bawah-config
            - secretRef:
                name: tropical-bawah-secret

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
