import { NavigationModule } from '../types/navigation';

export const MASTER_NAVIGATION: NavigationModule[] = [
  // 1. DASHBOARD
  {
    id: 'dashboard',
    name: 'Dashboard',
    path: '/dashboard',
    iconName: 'LayoutDashboard',
    description: 'Pusat Informasi & Command Center Bisnis Tropical Garden Resto',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
    submodules: [
      {
        id: 'overview',
        name: 'Command Center',
        path: '/dashboard',
        subParam: 'overview',
        description: 'Ringkasan performa real-time restoran sesuai tingkat kewenangan',
      },
    ],
  },

  // 2. TROPICAL HR
  {
    id: 'hr',
    name: 'Tropical HR',
    path: '/hr',
    iconName: 'Users',
    description: 'Human Resource, Presensi, Jadwal, SOP, KPI, dan Slip Gaji',
    badge: '14 Fitur',
    badgeColor: 'purple',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
    submodules: [
      {
        id: 'hr-dashboard',
        name: 'HR Dashboard',
        path: '/hr',
        subParam: 'dashboard',
        description: 'Pusat komando eksekutif & operasional SDM, presensi harian, antrean persetujuan, dan status kontrak',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'employees',
        name: 'Employee',
        path: '/hr',
        subParam: 'employees',
        description: 'Direktori data profil dan kepegawaian seluruh karyawan',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'organization',
        name: 'Organization',
        path: '/hr',
        subParam: 'organization',
        description: 'Struktur organisasi dan hierarki tim Tropical Garden Resto',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'attendance',
        name: 'Attendance',
        path: '/hr',
        subParam: 'attendance',
        description: 'Portal absensi real-time, log kehadiran, dan rekap shift',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'shifts',
        name: 'Shift & Schedule',
        path: '/hr',
        subParam: 'shifts',
        description: 'Kalender jadwal kerja, pergantian shift, dan roster mingguan',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'breaks',
        name: 'Break Management',
        path: '/hr',
        subParam: 'breaks',
        description: 'Manajemen istirahat staf, Standard Break (60m), Additional Break approval & audit log',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'overtime',
        name: 'Overtime Management',
        path: '/hr',
        subParam: 'overtime',
        description: 'Surat Perintah Lembur (SPL), approval workflow, hitung jam aktual & estimasi payroll lembur',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'configuration',
        name: 'HR Configuration',
        path: '/hr',
        subParam: 'configuration',
        description: 'Master konfigurasi shift, toleransi presensi, tarif potongan keterlambatan, geofence GPS, dan aturan lembur',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
      {
        id: 'payroll',
        name: 'Payroll & Penggajian Resto',
        path: '/hr',
        subParam: 'payroll',
        description: 'Manajemen penggajian, tunjangan, kalkulasi lembur, dan slip gaji (Khusus GM & HR)',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
      {
        id: 'sop',
        name: 'SOP',
        path: '/hr',
        subParam: 'sop',
        description: 'Standard Operating Procedure resmi Tropical Garden Resto',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'job-description',
        name: 'Job Description',
        path: '/hr',
        subParam: 'job-description',
        description: 'Uraian tugas pokok dan tanggung jawab setiap posisi',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'ika',
        name: 'IKA',
        path: '/hr',
        subParam: 'ika',
        description: 'Instruksi Kerja Alat dan panduan teknis operasional stasiun',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'checklist',
        name: 'Checklist HR',
        path: '/hr',
        subParam: 'checklist',
        description: 'Template dan penugasan checklist berkala SDM',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'kpi',
        name: 'KPI Personal',
        path: '/hr',
        subParam: 'kpi',
        description: 'Indikator kinerja utama dan skor evaluasi berkala karyawan',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'documents',
        name: 'HR Documents',
        path: '/hr',
        subParam: 'documents',
        description: 'Arsip dokumen internal, sertifikasi, kontrak, dan regulasi',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'reports',
        name: 'HR Reports',
        path: '/hr',
        subParam: 'reports',
        description: 'Laporan rekapitulasi kehadiran, kinerja, dan disiplin SDM',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
    ],
  },

  // 3. TROPICAL CRM
  {
    id: 'crm',
    name: 'Tropical CRM',
    path: '/crm',
    iconName: 'MessageSquare',
    description: 'Customer Relationship, WhatsApp Hub, Pipeline, dan Reservasi Meja',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
    allowedDepartments: ['Executive', 'Management', 'CRM', 'Service'],
    submodules: [
      {
        id: 'crm-dashboard',
        name: 'Dashboard CRM',
        path: '/crm',
        subParam: 'dashboard',
        description: 'Pusat komando CRM, radar reservasi hari ini, pipeline deals, AI follow-up & channel analytics',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'whatsapp-chat',
        name: 'WhatsApp Web & Chat',
        path: '/crm',
        subParam: 'whatsapp',
        description: 'Direct messaging WhatsApp Web, sinkronisasi kontak tamu, dan log percakapan',
        badge: 'Chat',
        badgeColor: 'emerald',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'whatsapp-blast',
        name: 'WhatsApp Blast',
        path: '/crm',
        subParam: 'blast',
        description: 'Kirim broadcast massal AI, blast voucher promo, dan pengingat reservasi ke segmen tamu',
        badge: 'Blast',
        badgeColor: 'purple',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'whatsapp-qr',
        name: 'WhatsApp Login (QR)',
        path: '/crm',
        subParam: 'whatsapp-qr',
        description: 'Pindai kode QR WhatsApp Multi-Device, manajemen perangkat tertaut, dan status webhook',
        badge: 'QR Code',
        badgeColor: 'blue',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'reservation-calendar',
        name: 'Kalender Reservasi Meja',
        path: '/crm',
        subParam: 'reservation-calendar',
        description: 'Penjadwalan meja VIP, arisan, corporate gathering, dan tracking DP',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'follow-up-calendar',
        name: 'Kalender Follow-Up CRM',
        path: '/crm',
        subParam: 'follow-up-calendar',
        description: 'Jadwal follow-up proposal penawaran, sapaan ulang tahun, dan nurturing tamu',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'customers',
        name: 'Customer Database',
        path: '/crm',
        subParam: 'customers',
        description: 'Database pelanggan, preferensi menu, dan histori kunjungan',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'leads',
        name: 'Leads & Prospecting',
        path: '/crm',
        subParam: 'leads',
        description: 'Pencatatan prospek tamu baru, gathering, dan event corporate',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'pipeline',
        name: 'Deals Pipeline',
        path: '/crm',
        subParam: 'pipeline',
        description: 'Kanban tracking deals gathering, paket pernikahan, dan reservasi VIP',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
    ],
  },

  // 4. OPERATIONS
  {
    id: 'operations',
    name: 'Operations',
    path: '/operations',
    iconName: 'UtensilsCrossed',
    description: 'Checklist Harian, Shift, Kitchen, Bar, Service, Cleaning, Stock & Wasting',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
    submodules: [
      {
        id: 'checklist',
        name: 'Daily Checklist',
        path: '/operations',
        subParam: 'checklist',
        description: 'Checklist kesiapan opening, running, dan closing stasiun',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'shift',
        name: 'Shift Operations',
        path: '/operations',
        subParam: 'shift',
        description: 'Handover catatan antar shift dan monitoring kelancaran lantai resto',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'kitchen',
        name: 'Kitchen',
        path: '/operations',
        subParam: 'kitchen',
        description: 'Stasiun dapur utama, mise en place, dan antrean pesanan masakan',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'bar',
        name: 'Bar',
        path: '/operations',
        subParam: 'bar',
        description: 'Stasiun minuman & kopi, standar penyajian, dan sanitasi bar',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'service',
        name: 'Service',
        path: '/operations',
        subParam: 'service',
        description: 'Pelayanan meja, standar keramahan, table setting, dan kepuasan tamu',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'cleaning',
        name: 'Cleaning & Dishwash',
        path: '/operations',
        subParam: 'cleaning',
        description: 'Sterilisasi peralatan makan, sanitasi toilet, dan jadwal deep clean',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'purchasing',
        name: 'Purchasing',
        path: '/operations',
        subParam: 'purchasing',
        description: 'Purchase Request (PR), Purchase Order (PO), dan penerimaan barang supplier',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'inventory',
        name: 'Inventory',
        path: '/operations',
        subParam: 'inventory',
        description: 'Stock opname, kartu stok bahan baku, dan peringatan minimum stock',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'recipes',
        name: 'Recipe Management',
        path: '/operations',
        subParam: 'recipes',
        description: 'Katalog Master Resep, Bill of Materials (BOM), porsi, dan histori versi',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'production',
        name: 'Batch Production',
        path: '/operations',
        subParam: 'production',
        description: 'Batching bumbu dasar, olahan setengah jadi, target yield & deviasi resep',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'wasting',
        name: 'Wasting',
        path: '/operations',
        subParam: 'wasting',
        description: 'Pencatatan bahan terbuang/rusak disertai bukti foto & analisa penyebab',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'issues',
        name: 'Operational Issues',
        path: '/operations',
        subParam: 'issues',
        description: 'Pencatatan insiden operasional, SLA tracking, eskalasi, dan verifikasi penyelesaian',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
    ],
  },

  // 5. FINANCE
  {
    id: 'finance',
    name: 'Finance',
    path: '/finance',
    iconName: 'BadgeDollarSign',
    description: 'Revenue, Cashier Reconcile, HPP Resep, Beban OPEX, dan Profitability',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
    allowedDepartments: ['Executive', 'Management', 'Finance', 'Operations', 'Service'],
    submodules: [
      {
        id: 'revenue',
        name: 'Revenue',
        path: '/finance',
        subParam: 'revenue',
        description: 'Omzet harian, rincian pembayaran (Tunai, QRIS, EDC, Transfer), dan tren',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'cashier',
        name: 'Cashier',
        path: '/finance',
        subParam: 'cashier',
        description: 'Input rekonsiliasi kasir, setoran kas, dan verifikasi selisih kas',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'hpp',
        name: 'HPP',
        path: '/finance',
        subParam: 'hpp',
        description: 'Kalkulator Harga Pokok Penjualan, resep baku, dan food cost percentage',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'expenses',
        name: 'Expenses',
        path: '/finance',
        subParam: 'expenses',
        description: 'Pencatatan beban operasional (OPEX), utilitas, dan petty cash resto',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'reports',
        name: 'Financial Reports',
        path: '/finance',
        subParam: 'reports',
        description: 'Laporan Laba Rugi, Cash Flow harian, dan ringkasan finansial',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'profitability',
        name: 'Profitability',
        path: '/finance',
        subParam: 'profitability',
        description: 'Analisa EBITDA, Net Profit Margin, dan Margin Kontribusi Menu',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
    ],
  },

  // 6. DEVELOPMENT
  {
    id: 'development',
    name: 'Development',
    path: '/development',
    iconName: 'GraduationCap',
    description: 'Business Academy, Assessment, Action Plan, Progress, Branding & Promo',
    allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
    submodules: [
      {
        id: 'business-academy',
        name: 'Business Academy',
        path: '/development',
        subParam: 'business-academy',
        description: 'Pusat pembelajaran strategi bisnis, hospitality, dan standar resto',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'hr-academy',
        name: 'HR Academy',
        path: '/development',
        subParam: 'hr-academy',
        description: 'Modul pelatihan kepemimpinan, komunikasi, dan pengembangan staf',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'assessment',
        name: 'Business Assessment',
        path: '/development',
        subParam: 'assessment',
        description: 'Audit kesehatan 8 pilar bisnis Tropical Garden Resto & identifikasi celah',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'action-plan',
        name: 'Action Plan',
        path: '/development',
        subParam: 'action-plan',
        description: 'Matriks inisiatif perbaikan terstruktur berdasarkan hasil audit',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR'],
      },
      {
        id: 'task',
        name: 'Task',
        path: '/development',
        subParam: 'task',
        description: 'Distribusi tugas peningkatan kualitas dan penugasan personal',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'progress',
        name: 'Progress',
        path: '/development',
        subParam: 'progress',
        description: 'Pemantauan realisasi eksekusi rencana aksi terhadap target waktu',
        allowedRoles: ['OWNER', 'MANAGER', 'SUPERVISOR', 'STAFF'],
      },
      {
        id: 'branding',
        name: 'Branding',
        path: '/development',
        subParam: 'branding',
        description: 'Panduan identitas merek Tropical Garden, tone of voice, dan aset visual',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
      {
        id: 'marketing',
        name: 'Marketing',
        path: '/development',
        subParam: 'marketing',
        description: 'Strategi pemasaran, kolaborasi influencer, dan positioning menu',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
      {
        id: 'promotion',
        name: 'Promotion',
        path: '/development',
        subParam: 'promotion',
        description: 'Kalender program promosi diskon, seasonal festival, dan loyalty reward',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
    ],
  },

  // 7. CONTENT CREATOR
  {
    id: 'content',
    name: 'Content Creator',
    path: '/content',
    iconName: 'Video',
    description: 'Kalender Konten Medsos, Brief Task, Kampanye, Produksi & Performa',
    allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
    allowedDepartments: ['Executive', 'Management', 'Marketing'],
    requiredResponsibilities: ['Social Media Production'],
    submodules: [
      {
        id: 'calendar',
        name: 'Content Calendar',
        path: '/content',
        subParam: 'calendar',
        description: 'Jadwal posting konten mingguan di Instagram, TikTok, dan YouTube',
        allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
      },
      {
        id: 'tasks',
        name: 'Content Task',
        path: '/content',
        subParam: 'tasks',
        description: 'Daftar penugasan pembuatan script, ide video, dan copywriting',
        allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
      },
      {
        id: 'campaign',
        name: 'Campaign',
        path: '/content',
        subParam: 'campaign',
        description: 'Manajemen kampanye tematik (Menu Baru, Ramadan, Musim Liburan)',
        allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
      },
      {
        id: 'production',
        name: 'Production',
        path: '/content',
        subParam: 'production',
        description: 'Pipeline shooting, editing video reels/TikTok, dan review approval',
        allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
      },
      {
        id: 'performance',
        name: 'Performance',
        path: '/content',
        subParam: 'performance',
        description: 'Analisa views, engagement rate, share, dan efektivitas konten',
        allowedRoles: ['OWNER', 'MANAGER', 'STAFF'],
      },
    ],
  },

  // 8. DIGITAL MARKETING (MANAGER ONLY)
  {
    id: 'marketing',
    name: 'Digital Marketing',
    path: '/marketing',
    iconName: 'TrendingUp',
    description: 'Ads Budget, ROAS, Kampanye Promo, Google Maps GMB, & Influencer KOL (Manager Only)',
    badge: 'Manager Only',
    badgeColor: 'pink',
    allowedRoles: ['OWNER', 'MANAGER'],
    submodules: [
      {
        id: 'marketing-overview',
        name: 'Marketing Dashboard',
        path: '/marketing',
        subParam: 'overview',
        description: 'Pusat pantauan Ads Spend, ROAS, Promo, GMB & KOL',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
    ],
  },

  // 9. REPORTS (MBR)
  {
    id: 'reports',
    name: 'Reports',
    path: '/reports',
    iconName: 'FileBarChart',
    description: 'Monthly Business Review (MBR) & Laporan Komprehensif Eksekutif',
    allowedRoles: ['OWNER', 'MANAGER'],
    submodules: [
      {
        id: 'mbr',
        name: 'Monthly Business Review',
        path: '/reports',
        subParam: 'mbr',
        description: 'Tinjauan performa bulanan: Finansial, Operasional, CRM, SDM & Marketing',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
    ],
  },

  // 11. SETTINGS
  {
    id: 'settings',
    name: 'Settings',
    path: '/settings',
    iconName: 'Settings',
    description: 'Pengaturan Sistem, Hak Akses, Master Konfigurasi, dan Profil Pengguna',
    allowedRoles: ['OWNER', 'MANAGER'],
    submodules: [
      {
        id: 'general',
        name: 'General Settings',
        path: '/settings',
        subParam: 'general',
        description: 'Konfigurasi profil restoran, jam operasional, dan parameter sistem',
        allowedRoles: ['OWNER', 'MANAGER'],
      },
    ],
  },
];
