<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // Meat & Poultry
            [
                'sku' => 'RAW-MEAT-TENDERLOIN-01',
                'name' => 'Daging Tenderloin Sapi Lokal',
                'category' => 'MEAT',
                'unit' => 'Kg',
                'current_stock' => 25.5000,
                'minimum_stock' => 10.0000,
                'maximum_stock' => 50.0000,
                'reorder_point' => 15.0000,
                'average_cost' => 145000.00,
                'last_purchase_cost' => 148000.00,
                'storage_location' => 'Freezer Utama A',
            ],
            [
                'sku' => 'RAW-MEAT-SIRLOIN-01',
                'name' => 'Daging Sirloin Sapi Lokal',
                'category' => 'MEAT',
                'unit' => 'Kg',
                'current_stock' => 30.0000,
                'minimum_stock' => 12.0000,
                'maximum_stock' => 60.0000,
                'reorder_point' => 18.0000,
                'average_cost' => 125000.00,
                'last_purchase_cost' => 127000.00,
                'storage_location' => 'Freezer Utama A',
            ],
            [
                'sku' => 'RAW-PLT-CHICKEN-FILLET-01',
                'name' => 'Dada Ayam Fillet Segar',
                'category' => 'POULTRY',
                'unit' => 'Kg',
                'current_stock' => 45.0000,
                'minimum_stock' => 15.0000,
                'maximum_stock' => 80.0000,
                'reorder_point' => 25.0000,
                'average_cost' => 48000.00,
                'last_purchase_cost' => 50000.00,
                'storage_location' => 'Chiller 1 Dapur',
            ],
            [
                'sku' => 'RAW-PLT-CHICKEN-WHOLE-01',
                'name' => 'Ayam Kampung Utuh (Potong 4)',
                'category' => 'POULTRY',
                'unit' => 'Ekor',
                'current_stock' => 20.0000,
                'minimum_stock' => 8.0000,
                'maximum_stock' => 40.0000,
                'reorder_point' => 12.0000,
                'average_cost' => 65000.00,
                'last_purchase_cost' => 65000.00,
                'storage_location' => 'Chiller 1 Dapur',
            ],

            // Seafood
            [
                'sku' => 'RAW-SFD-GURAME-01',
                'name' => 'Ikan Gurame Segar (500-600 gr)',
                'category' => 'SEAFOOD',
                'unit' => 'Ekor',
                'current_stock' => 35.0000,
                'minimum_stock' => 15.0000,
                'maximum_stock' => 60.0000,
                'reorder_point' => 20.0000,
                'average_cost' => 38000.00,
                'last_purchase_cost' => 40000.00,
                'storage_location' => 'Chiller Seafood',
            ],
            [
                'sku' => 'RAW-SFD-NILA-01',
                'name' => 'Ikan Nila Merah Segar (350-400 gr)',
                'category' => 'SEAFOOD',
                'unit' => 'Ekor',
                'current_stock' => 50.0000,
                'minimum_stock' => 20.0000,
                'maximum_stock' => 90.0000,
                'reorder_point' => 30.0000,
                'average_cost' => 18000.00,
                'last_purchase_cost' => 19000.00,
                'storage_location' => 'Chiller Seafood',
            ],
            [
                'sku' => 'RAW-SFD-UDANG-WINDU-01',
                'name' => 'Udang Windu Size 30',
                'category' => 'SEAFOOD',
                'unit' => 'Kg',
                'current_stock' => 18.0000,
                'minimum_stock' => 6.0000,
                'maximum_stock' => 30.0000,
                'reorder_point' => 10.0000,
                'average_cost' => 110000.00,
                'last_purchase_cost' => 115000.00,
                'storage_location' => 'Freezer Seafood',
            ],
            [
                'sku' => 'RAW-SFD-CUMI-01',
                'name' => 'Cumi-Cumi Segar Tube Ringan',
                'category' => 'SEAFOOD',
                'unit' => 'Kg',
                'current_stock' => 15.0000,
                'minimum_stock' => 5.0000,
                'maximum_stock' => 25.0000,
                'reorder_point' => 8.0000,
                'average_cost' => 85000.00,
                'last_purchase_cost' => 88000.00,
                'storage_location' => 'Freezer Seafood',
            ],

            // Beverage & Coffee
            [
                'sku' => 'RAW-BEV-ESPRESSO-BLEND-01',
                'name' => 'House Blend Coffee Beans (70:30 Arabica-Robusta)',
                'category' => 'BEVERAGE',
                'unit' => 'Kg',
                'current_stock' => 28.0000,
                'minimum_stock' => 10.0000,
                'maximum_stock' => 50.0000,
                'reorder_point' => 15.0000,
                'average_cost' => 185000.00,
                'last_purchase_cost' => 190000.00,
                'storage_location' => 'Bar Dry Shelf A',
            ],
            [
                'sku' => 'RAW-BEV-FRESH-MILK-01',
                'name' => 'Fresh Milk Pasteurized 1 Liter',
                'category' => 'DAIRY',
                'unit' => 'Pack',
                'current_stock' => 60.0000,
                'minimum_stock' => 24.0000,
                'maximum_stock' => 120.0000,
                'reorder_point' => 36.0000,
                'average_cost' => 18500.00,
                'last_purchase_cost' => 19000.00,
                'storage_location' => 'Chiller Bar Under-counter',
            ],
            [
                'sku' => 'RAW-BEV-SYRUP-PALM-01',
                'name' => 'Gula Aren Organik Liquid 1L',
                'category' => 'BEVERAGE',
                'unit' => 'Botol',
                'current_stock' => 15.0000,
                'minimum_stock' => 5.0000,
                'maximum_stock' => 30.0000,
                'reorder_point' => 8.0000,
                'average_cost' => 35000.00,
                'last_purchase_cost' => 35000.00,
                'storage_location' => 'Bar Dry Shelf B',
            ],
            [
                'sku' => 'RAW-BEV-TEA-JASMINE-01',
                'name' => 'Premium Jasmine Tea Leaves',
                'category' => 'BEVERAGE',
                'unit' => 'Kg',
                'current_stock' => 12.0000,
                'minimum_stock' => 4.0000,
                'maximum_stock' => 20.0000,
                'reorder_point' => 6.0000,
                'average_cost' => 65000.00,
                'last_purchase_cost' => 65000.00,
                'storage_location' => 'Bar Dry Shelf A',
            ],

            // Dry Goods & Condiments
            [
                'sku' => 'RAW-DRY-RICE-PANDAN-01',
                'name' => 'Beras Pandan Wangi Premium 25Kg',
                'category' => 'DRY_GOODS',
                'unit' => 'Karung',
                'current_stock' => 10.0000,
                'minimum_stock' => 3.0000,
                'maximum_stock' => 15.0000,
                'reorder_point' => 4.0000,
                'average_cost' => 375000.00,
                'last_purchase_cost' => 380000.00,
                'storage_location' => 'Dry Store Room A',
            ],
            [
                'sku' => 'RAW-DRY-COOKING-OIL-01',
                'name' => 'Minyak Goreng Sawit 18 Liter (Jerigen)',
                'category' => 'DRY_GOODS',
                'unit' => 'Jerigen',
                'current_stock' => 8.0000,
                'minimum_stock' => 3.0000,
                'maximum_stock' => 12.0000,
                'reorder_point' => 4.0000,
                'average_cost' => 265000.00,
                'last_purchase_cost' => 270000.00,
                'storage_location' => 'Dry Store Room B',
            ],
            [
                'sku' => 'RAW-DRY-SALT-01',
                'name' => 'Garam Meja Beryodium 1Kg',
                'category' => 'DRY_GOODS',
                'unit' => 'Bungkus',
                'current_stock' => 25.0000,
                'minimum_stock' => 10.0000,
                'maximum_stock' => 40.0000,
                'reorder_point' => 12.0000,
                'average_cost' => 6500.00,
                'last_purchase_cost' => 7000.00,
                'storage_location' => 'Dapur Spice Rack',
            ],
            [
                'sku' => 'RAW-DRY-SUGAR-01',
                'name' => 'Gula Pasir Kristal Putih 50Kg',
                'category' => 'DRY_GOODS',
                'unit' => 'Karung',
                'current_stock' => 4.0000,
                'minimum_stock' => 2.0000,
                'maximum_stock' => 8.0000,
                'reorder_point' => 2.0000,
                'average_cost' => 750000.00,
                'last_purchase_cost' => 760000.00,
                'storage_location' => 'Dry Store Room A',
            ],

            // Packaging
            [
                'sku' => 'PKG-BOX-BENTO-01',
                'name' => 'Kotak Makanan Bento Eco-Kraft 4 Sekat',
                'category' => 'PACKAGING',
                'unit' => 'Pcs',
                'current_stock' => 350.0000,
                'minimum_stock' => 100.0000,
                'maximum_stock' => 800.0000,
                'reorder_point' => 150.0000,
                'average_cost' => 2400.00,
                'last_purchase_cost' => 2500.00,
                'storage_location' => 'Packaging Store Room',
            ],
            [
                'sku' => 'PKG-CUP-PAPER-16OZ-01',
                'name' => 'Paper Cup 16oz Cold Drink + Lid',
                'category' => 'PACKAGING',
                'unit' => 'Set',
                'current_stock' => 500.0000,
                'minimum_stock' => 200.0000,
                'maximum_stock' => 1200.0000,
                'reorder_point' => 300.0000,
                'average_cost' => 1200.00,
                'last_purchase_cost' => 1250.00,
                'storage_location' => 'Packaging Store Room',
            ],
        ];

        foreach ($items as $item) {
            DB::table('inventory_items')->insert([
                'uuid' => (string) Str::uuid(),
                'sku' => $item['sku'],
                'name' => $item['name'],
                'category' => $item['category'],
                'unit' => $item['unit'],
                'current_stock' => $item['current_stock'],
                'minimum_stock' => $item['minimum_stock'],
                'maximum_stock' => $item['maximum_stock'],
                'reorder_point' => $item['reorder_point'],
                'average_cost' => $item['average_cost'],
                'last_purchase_cost' => $item['last_purchase_cost'],
                'storage_location' => $item['storage_location'],
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
